import{a as p,i as a,S as u}from"./assets/vendor-797c93b9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y=document.querySelector(".gallery");function h(t){const o=t.hits.map(s=>`<li class="gallery-item" data-id="${s.id}">
        <div class="img-container" >
        <a class="large-image" href="${s.largeImageURL}">
        <img class="image" src="${s.webformatURL}" alt="${s.tags}">
        </a> 
        </div>
        <ul class="description-list" >
          <li class="description-item"><p>Likes</p><p>${s.likes}</p></li>
          <li class="description-item"><p>Views</p><p>${s.views}</p></li>
          <li class="description-item"><p>Comments</p><p>${s.comments}</p></li>
          <li class="description-item"><p>Downloads</p><p>${s.downloads}</p></li>
        </ul>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o)}const n=document.querySelector(".loader"),w=15;let m,g,i=1,l;async function b(t){l=t.target.elements.search.value.trim(),i=1;try{n.classList.remove("is-hidden");const o=await p.get("https://pixabay.com/api/",{params:{key:"42614843-af27c28624474ca020601ef6c",q:l,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:i}});o.data.hits.length===0?a.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",position:"topCenter"}):(h(o.data),document.querySelector(".more-btn").classList.remove("is-hidden")),n.classList.add("is-hidden"),new u(".large-image",{captionDelay:250,captionsData:"alt"}).refresh()}catch{a.show({message:"Sorry, something goes wrong!",backgroundColor:"red",messageColor:"white",position:"topCenter"})}}async function L(t){i+=1;try{n.classList.remove("is-hidden");const o=await p.get("https://pixabay.com/api/",{params:{key:"42614843-af27c28624474ca020601ef6c",q:l,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:i}});m=o.data.totalHits,g=Math.ceil(m/w),o.data.hits.length===0?a.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",position:"topCenter"}):(h(o.data),g<=i&&(document.querySelector(".more-btn").classList.add("is-hidden"),a.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"red",messageColor:"white",position:"topCenter"})),C()),n.classList.add("is-hidden"),new u(".large-image",{captionDelay:250,captionsData:"alt"}).refresh()}catch{}}function C(){const t=document.querySelector(".gallery-item"),o=t==null?void 0:t.getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}const f=document.querySelector(".form"),v=document.querySelector(".more-btn");f.addEventListener("submit",S);v.addEventListener("click",q);function S(t){t.preventDefault(),t.target.elements.search.value===""?a.show({message:"You have to text something",backgroundColor:"red",messageColor:"white",position:"topCenter"}):(document.querySelector(".gallery").innerHTML="",b(t)),f.reset()}function q(t){L()}
//# sourceMappingURL=commonHelpers.js.map
